### PR TITLE
[WIP] Upgrade & rewrite rest-server

### PR DESCRIPTION
**Pull request by jooola**
I wanted to clean the project and rewrite it by splitting the project in more files, moving server code in the library section (not in the cmd folders).

I replaced the build.go with goreleaser to produce binaries and publish them to github. Docker can be added to the process too.

I switched to gorilla/mux since the old mux library wasn't getting any update.

Still needs some cleanup and global review in order to correct few things I might have changed too radically.

Off course I hope this PR can break compatibility by releasing a new major version

### CODE REVIEW

**Comment by rawtaz** [comment]
Thanks for your efforts @jooola. Were these changes discussed anywhere though?

**Comment by jooola** [comment]
@rawtaz Nope, this was just a little rewrite on some free time. I didn't discussed this anywhere. Still this can be done on this thread.

**Comment by gbolo** [comment]
Hi @rawtaz @jooola 

is this project active? I noticed that the latest docker tag (0.9.8) didn't update the `VERSION` file, so the binary still reports the older version. Also the docker image has not been pushed for a while, so some flags (like `--no-auth`) don't work. i built the latest tag locally and even the `DISABLE_AUTHENTICATION` does not seem to do anything (the entrypoint tries to delete a non-existing file).

Anyways, I would like to fix some issues i see. I been using this for a few hours now, and I really like this product. But we should merge this before I PR any fixes.

Thanks

**Comment by rawtaz** [comment]
I just got access to this repository, but yes it is "active" in the sense that if anything major happens and needs fixing we will deal with it.

However, your PR is not really the best thing since sliced bread. It might contain great changes, but you shouldn't have made it this huge and without any previous discussions.

You should have created one issue for each individual change you were considering, gathered other people's input, then depending on the outcome of those, created one PR per change.

That way everyone is on board, all changes are such that are wanted and discussed, and the are individually tracked as well as individually merged.

You do have your changes split up in separate commits which is great, but it's not the same thing. It's now all in one big PR.

**Comment by rawtaz** [comment]
For example, the Dockerfile thing you mention; Create an issue describing the problem, what you expect to see and what you are seeing instead, and suggest an action if you have such thoughts. Then after some comments (or if you are sure that your proposed solution is what others will think is good and accept) file a PR, which can then be merged.

**Comment by gbolo** [comment]
@rawtaz I dont have anything to do with this PR, i just noticed it was a huge one which refactored everything, thats why I was waiting. I offer to make PRs because the activity level for this project seems to be low, which usualy means `help wanted and appreciated`.

I will open some issues, thanks.

**Comment by rawtaz** [comment]
@gbolo You are right, I confused you with @jooola, I'm sorry about that!

Indeed, your help is welcome :) So is @jooola's, but we need it in a more digestable format than this PR :)

Starting some issues for the individual areas of improvement is a very good start!

**Comment by gbolo** [comment]
in terms of this PR, I feel it does much to modernize this go project. Improvements to builds and dependancies are worth it. But perhap split that out to other PRs?

**Comment by jooola** [comment]
Hey, nice I though this PR will be lost with the other long living PR's.
 
> However, your PR is not really the best thing since sliced bread. It might contain great changes, but you shouldn't have made it this huge and without any previous discussions.

I was lazy making a clean PR since I made some drastic changes and I didn't though maintainers will be interested in it. This mainly was for my own usage. But I'm happy if some cleanup and splitting will get those changes merged.

I usually follow any opensource contributing guidelines, even if sometime they tend to be a bit hard for fast contributions. This might scare some contributors from small repos (less crowded) such as this one. Anyway that's no excuse, I was lazy.

Give me a few days to split everything in small PR's, and I'd be happy to help releasing a new major version with some release candidate.

Still I'd like some input on the substance, we mainly talked about the form right now.

**Comment by jooola** [comment]
I create few pull requests, please see #99 and #100 

The whole server rewrite will take more time to split, I think I'll describe the changes but not necessarily split everything is tiny commits.

**Comment by rawtaz** [comment]
@jooola Thanks for splitting up the PR into separate PRs, one for each individual change. But we also need the corresponding issues for them. That way:

- The suggested change is discussed in the issue, and in case the final conclusion on how to implement it deviates from the original suggestion, work in a PR doesn't have to be wasted and the PR doesn't have to be reviewed multiple times (reviewing PRs is often considered more time consuming for the core developers than writing the code themselves).

- Also, in case the suggested change isn't agreed upon (i.e. won't be accepted even in a different way than originally intended), work in a PR isn't wasted if this conclusion has been reached in a more general discussion in the issue beforehand.

- Once it's been concluded that the change should be made/implemented, the actual implementation work and the code can be discussed in the PR. This is a different type of discussion than in the issue.

So, it makes sense to keep these discussions separate, and to start with the change suggestion in the issue. I'm sorry if this was unclear in the issue/PR templates, I will review those right now to make sure.

Can you please make an issue for each of the individual PRs?

**Comment by fd0** [comment]
This PR hasn't seen any activity for several months now, I'm going to close it for now. Please feel free to add further comments, thanks!

**Pull request closed without merging**
