### PR TITLE
reload htpasswd on SIGHUP

### PR DESCRIPTION
**Pull request by qbit**
This lets one send SIGHUP to `rest-server` to force it to reload the `.htpasswd` file.

### CODE REVIEW

**Comment by wojas** [comment]
LGTM!

**Comment by stappersg** [comment]
Comment is only for mentioning #80

**Comment by Framsfex** [comment]
Where can I find this feature in the documentation?!

**Comment by MichaelEischer** [comment]
Judging from a quick search, the answer is nowhere. Feel free to add some docs.

**Pull request merged**
