### PR TITLE
Issue templates: how to get version using docker

### PR DESCRIPTION
**Pull request by jtagcat**
Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
No, but I think it's not needed.

Checklist
---------

- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))
- [ ] I have run `gofmt` on the code in all commits
- [?] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/rest-server/commits/master)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by rawtaz** [comment]
@jtagcat What is `docker images restic/rest-server -q` supposed to do, exactly?

Besides that, we can't have the text changed the way it currently is in this PR, the heading becomes way too large/long.

**Comment by jtagcat** [comment]
It outputs the latest image id, docker equivalent of version. `-q` outputs just the id, instead of the repo, tag, image id and size along with the header.

**Comment by rawtaz** [comment]
Right, I didn't see that because I hadn't pulled the image yet, silly.

Can you update the PR so that your addition/changes are instead embedded in a comment?

**Comment by jtagcat** [comment]
> Right, I didn't see that because I hadn't pulled the image yet, silly.
> 
> Can you update the PR so that your addition/changes are instead embedded in a comment?

Done.

**Comment by rawtaz** [comment]
Thanks! I'd like to merge this, but please squash and rebase it on master first. Five commits for two line changes is a bit too much for those of us that are picky :)

**Comment by wojas** [comment]
@rawtaz You can select squash during the PR merge.

**Comment by rawtaz** [comment]
It's unfortunately not the same thing. Choosing that option makes GitHub not create a merge commit, which we want in this case.

I can do the squash assuming you enabled maintainer commit access to the PR/branch :)

**Comment by jtagcat** [comment]
> It's unfortunately not the same thing. Choosing that option makes GitHub not create a merge commit, which we want in this case.
> 
> I can do the squash assuming you enabled maintainer commit access to the PR/branch :)

I did.

I also tried squashing myself, but still got noop in rebase -i. After an hour I temporarily give up. No idea why can't I squash.

**Comment by rawtaz** [comment]
@jtagcat I noticed you had made a merge commit from upstream/master into your own master. It was too messy to fix this so instead I created a local branch, cherry-picked and squashed your non-merge commits relating to this PR/change, and created a manual merge commit with it in the upstream/master branch.

The best way to make a PR is to: 1) always create a new feature branch for your changes, and add your changes/commits to that branch; 2) push that branch to your fork of the upstream repository on GitHub; 3) open the PR with that branch as the base. That will work great :)

**Pull request closed without merging**
