### PR TITLE
[WIP] Prometheus metrics

### PR DESCRIPTION
**Pull request by wojas**
**This is a work in progress**

Exposes a few metrics for Prometheus under /metrics if started with --prometheus.

## TODO

- Figure out how to use gopkg to manage vendor dependencies (currently directly copied into repo - this does add quite a bit of vendor cruft)
- Some more metrics

Example:

    # HELP rest_server_blob_read_bytes_total Total number of bytes read from blobs
    # TYPE rest_server_blob_read_bytes_total counter
    rest_server_blob_read_bytes_total{repo="test",type="data"} 2.13557024e+09
    rest_server_blob_read_bytes_total{repo="test",type="index"} 1.198653e+06
    rest_server_blob_read_bytes_total{repo="test",type="keys"} 5388
    rest_server_blob_read_bytes_total{repo="test",type="locks"} 1975
    rest_server_blob_read_bytes_total{repo="test",type="snapshots"} 10018
    # HELP rest_server_blob_read_total Total number of blobs read
    # TYPE rest_server_blob_read_total counter
    rest_server_blob_read_total{repo="test",type="data"} 3985
    rest_server_blob_read_total{repo="test",type="index"} 21
    rest_server_blob_read_total{repo="test",type="keys"} 12
    rest_server_blob_read_total{repo="test",type="locks"} 12
    rest_server_blob_read_total{repo="test",type="snapshots"} 32
    # HELP rest_server_blob_write_bytes_total Total number of bytes written to blobs
    # TYPE rest_server_blob_write_bytes_total counter
    rest_server_blob_write_bytes_total{repo="test",type="data"} 1.063726179e+09
    rest_server_blob_write_bytes_total{repo="test",type="index"} 395586
    rest_server_blob_write_bytes_total{repo="test",type="locks"} 1975
    rest_server_blob_write_bytes_total{repo="test",type="snapshots"} 1933
    # HELP rest_server_blob_write_total Total number of blobs written
    # TYPE rest_server_blob_write_total counter
    rest_server_blob_write_total{repo="test",type="data"} 226
    rest_server_blob_write_total{repo="test",type="index"} 6
    rest_server_blob_write_total{repo="test",type="locks"} 12
    rest_server_blob_write_total{repo="test",type="snapshots"} 6

Two example Prometheus graphs (this would like nicer in Grafana):

prometheus write
prometheus read

### CODE REVIEW

**Comment by zcalusic** [comment]
This would be absolutely fantastic addition to Rest Server, @wojas! 👍 Thanks for your work!

Dependencies are easily pulled via dep ensure. And yes, the vendor folder is growing rapidly, but there's not much to do about that. Sometime in the future we might make decision that dep ensure is the first step before building, and remove vendor folder alltogether from the distribution, but I'm not ready yet for such bold move. 😅

Anyways, don't worry about dependencies, I will help you with them. Concentrate on good stuff, lemme do the grunt work. :)

**Comment by wojas** [comment]
@zcalusic Good to hear about the dependencies, I was most worried about that part. :-)

Feel free to push to this branch if you need to!

**Comment by zcalusic** [comment]
OK, it looks pretty clean. I can't test it right now, playing with Prometheus being still on my todo list, but the time will come, soon...

I'm merging it, please stay around in case some strange things start happening. 😄 

And most importantly, thanks for your contribution, this is really great stuff! 👍

**Comment by wojas** [comment]
@zcalusic I had some more changes coming up, but I'll add a new PR for that. 😄

**Comment by zcalusic** [comment]
Of course. Rest Server 1.0.0 has officialy been postponed, too many new features. 😃

**Pull request merged**
