### PR TITLE
Move main function into separate package

### LINKED ISSUE #12: Make importable
Hi, me again. :smile: I'm this 👌 close to having this implemented as a Caddy plugin, which will allow you to add the `restic` directive to your Caddyfile, so you can use HTTPS to transfer files instead of HTTP, without having to worry about certificates.

My motivation is to avoid relying on SFTP which gets slower and slower forever during the transfer, until the transfer takes weeks instead of hours. My hope and expectation is that HTTPS won't do this because it doesn't have the crazy flow control that SSH + SFTP layers on top of TCP's. Or something.

Anyway, one benefit of this being a Caddy plugin is that Caddy can just run indefinitely and keep the 
server going (instead of having to restart it to reload renewed certs), and also serve other websites on the same port too. (One alternative you could do is use [autocert](https://godoc.org/golang.org/x/crypto/acme/autocert) into your program, to get this feature without integrating with Caddy. Autocert requires only a couple lines of code.)

However, in order for me to use this as a library, I need to be able to import it. Specifically, I think I need access to the `setupMux()` function. And if the mux and handlers and stuff could be moved into a non-main package, then I could import it.

So, in summary, I'm requesting:

1. Move as much as possible out of the `main` package so it can be imported
2. Export `setupMux()` so it can be used by other packages in their own handlers

I think I could submit a PR if you're OK with this.

### PR DESCRIPTION
**Pull request by mholt**
This closes #12. It enables rest-server to be used as a library/middleware, which I'm using for a Caddy plugin.

I verified this compiles and the Caddy plugin is working splendidly! I'm currently using this to perform a backup.

### CODE REVIEW

**Comment by zcalusic** [comment]
I'm afraid the build is not working for me. Travis is not reflecting the reality properly here.

Doing the official ```go run build.go``` I find ```rest-server``` file in the current folder, but it's not the binary as expected, but ar archive?! Maybe @fd0 could help with this one, he's the original build.go developer?

Trying the usual go install ./cmd/rest-server ends with an error, too:
```
# github.com/restic/rest-server/cmd/rest-server
cmd/rest-server/main.go:31: undefined: falrestserver in falrestserver.Config
```

**Comment by mholt** [comment]
Oh... I didn't try using build.go, I guess I overlooked that script.

Looks like I fat fingered something in my editor after I compiled and ran it. I just pushed a better commit that actually builds.

**Comment by zcalusic** [comment]
```go run build.go``` still not working properly. @fd0 could you take a peek what's going on there?

In the meantime, I'll deploy the new version via ```go install``` and see how it works.

**Comment by fd0** [comment]
I'll take a look now.

**Comment by fd0** [comment]
Hu, sorry, I've got no idea what just happened.

**Comment by fd0** [comment]
I've created #16, push @mholt's commit and added a commit which fixes `build.go`. Please review :)

**Pull request closed without merging**
