### PR TITLE
Add support for multiple repositories in a folder

### LINKED ISSUE #107: Support subdirectories with --private-repos
What should rest-server do differently?
---------------------------------------

Currently only one level of username is supported with the `--private-repos` flag, e.g. `http://server/username` is supported but not `http://server/username/foo`, `http://server/username/foo/bar`, etc.

Rest-server should allow *at least* one additional level, e.g. `http://server/username/foo/bar`.

We should at the same time consider if there's a point in, and without too much complexity, possible to, make it accept any number of subdirectories, e.g. `http://server/username/foo/bar/star/har`.

What are you trying to do? What is your use case?
-------------------------------------------------

Example use case: https://github.com/restic/rest-server/issues/76#issuecomment-457291482

### PR DESCRIPTION
**Pull request by ruiztulio**
What is the purpose of this change? What does it change?
--------------------------------------------------------
This add suport for subdirectories because at the moment only is supported ```/repo```, now we can do ```/group/user``` for example.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Closes #107 

Checklist
---------

- [X] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/rest-server/commits/master)
- [ ] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by juanrgm** [comment]
What is the status of this? Some help?

**Comment by Du-St** [comment]
I would also appreciated some status info on this issue. Thanks!

**Comment by demlak** [comment]
#76 https://github.com/restic/rest-server/issues/76#issuecomment-494447042
Since latest release of rest-server breaks the linked workaround (there is a good reason for it), this pull-request gets more and more interessting for us, who already have such a "subdir-setup".
I can't see how far away this solution is. should i wait? should i change my setup? questions.. questions.. questions..

**Comment by elch86** [comment]
Happy new year everybody. Let me know where to send beer and pizza to speed this up, i am currently setting up a completely restic installation and would really appreciate if restic would incorporate the change.. means that i dont have to migrate my backup structure lateron ;)

**Comment by wojas** [comment]
PR #112 refactors the Server components and adds subrepositories in a generic way as part of that refactoring.

**Comment by fd0** [comment]
Superseded by #112

**Pull request closed without merging**
