### PR TITLE
Make rest-server compatible

### PR DESCRIPTION
**Pull request by fd0**
This PR adds the following changes:

 * Allow deleting config files
 * Directly write to the target file, with O_EXCL

### CODE REVIEW

**Comment by fd0** [comment]
Oh, I'm sorry, I should've added a few sentences.

The backend tests expect that when a file is written that is already present in the repo, an error is returned. At the moment the rest server will happily overwrite files. So there are several ways to do this:
 * Write to a tempfile, then use `stat()` to check if there's a file, and then rename the file. This is what the local backend does, and it's not that great (and racy).
 * Write to a tempfile, then use `renameat2()` with `RENAME_NOREPLACE`. This syscall is not available in Go at the moment.
 * Write to the target file, create it with `O_EXCL`, which fails when the file already exist. This is what my patch introduces and what I'm planning to add to the local backend.

What do you think?

**Comment by zcalusic** [comment]
Now, that you've explained it well, makes a lot of sense. :)

If it's true that no file in restic repo is ever overwritten (I really didn't know that fact!), which is implied by the backend test you refer to, then I must agree that using temporary file makes no sense at all.

Previously, I kept that part thinking that in many cases if write fails (due to network or similar), it is better to keep old file, than partial new file. But, if that can't happen by design, we should've never used temp file. :)

**Comment by zcalusic** [comment]
Apropos the 2nd commit, we already have CheckConfig(), GetConfig() and SaveConfig() functions, which is to say that config management is in many ways different from the rest of the API. This can also be seen from the REST API doc, although config is one of the valid types, methods on it are separately documented.

Maybe it would be a bit cleaner to then also add DeleteConfig() function to handle config removal, instead of hardcoding special case in DeleteBlob? And document it in the API separately too?

But, I'm just thinking loud at this point, don't have time to go into details right now, I must admit.

**Comment by fd0** [comment]
Agreed, I'm reworking the commit and add a `DeleteConfig()`, that's a better style.

**Comment by fd0** [comment]
Please have a look again.

**Comment by zcalusic** [comment]
LGTM. Let's test... :)

**Comment by fd0** [comment]
Looks good! https://travis-ci.org/restic/restic/builds/212411560

**Pull request merged**
