### PR TITLE
Move main function into separate package

### PR DESCRIPTION
**Pull request by fd0**
Continuation of #13, which was accidentally closed.

### CODE REVIEW

**Comment by zcalusic** [comment]
Oh, that was a simple tweak, I though it would be more complex. :)

**Comment by fd0** [comment]
Hm, we maybe want to move that again. At the moment the main package lives in `cmd/rest-server`, so people who install this via `go get` (not me) will have to do `go get github.com/restic/rest-server/cmd/rest-server` or `go get github.com/restic/rest-server/...`...

**Comment by zcalusic** [comment]
Oh, that is fine, and I've already documented that fact in the README. ```go install ./cmd/binary``` is as standard as it gets. Especially if you want to use a package both as library and also have executable(s).

**Comment by mholt** [comment]
Yeah, I've seen the `/cmd/foo` pattern a lot in Go projects so it can be built easily and have the right resulting filename without `-o`. But it's true, if you want to install the command, you need to do `go get github.com/restic/rest-server/cmd/rest-server`.

**Comment by fd0** [comment]
Fine with me, I'd just wanted to bring it up so we can decide we want it this way :)

**Pull request merged**
